spring:
  datasource:
    url: jdbc:mariadb://doyoueat.c5aisrsakolc.ap-northeast-2.rds.amazonaws.com/doyoueat
    username: doyoueat
    password: doyoueat96
    driver-class-name: org.mariadb.jdbc.Driver

  devtools:
      livereload:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace